sudo: required
services:
  - docker

script:
  - docker build -t superironpanda/node .
  - docker images superironpanda/node


before_deploy:
  - docker login -u superironpanda -p 7xLXzqh8nVVprsW

deploy:
  provider: script
  script: docker push superironpanda/node
  on:
    branch: master